# Titanic Survival Prediction

## Feature Engineering

Goal:
Create meaningful features that improve model performance and capture hidden patterns in passenger data.

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [2]:
from google.colab import files

uploaded = files.upload()

Saving test.csv to test.csv
Saving train.csv to train.csv

In [3]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

train.shape, test.shape

((891, 12), (418, 11))

In [4]:
test_ids = test["PassengerId"]

In [5]:
full = pd.concat(
    [train.drop("Survived", axis=1), test],
    axis=0,
    ignore_index=True
)

full.shape

(1309, 11)

In [6]:
full["Title"] = full["Name"].str.extract(
    " ([A-Za-z]+)\.",
    expand=False
)

<>:2: SyntaxWarning: invalid escape sequence '\.'
<>:2: SyntaxWarning: invalid escape sequence '\.'
/tmp/ipykernel_10798/3588531106.py:2: SyntaxWarning: invalid escape sequence '\.'
  " ([A-Za-z]+)\.",

In [7]:
full["Title"].value_counts()

Title
Mr          757
Miss        260
Mrs         197
Master       61
Rev           8
Dr            8
Col           4
Major         2
Mlle          2
Ms            2
Mme           1
Don           1
Sir           1
Lady          1
Capt          1
Countess      1
Jonkheer      1
Dona          1
Name: count, dtype: int64

In [8]:
rare_titles = [
    "Lady",
    "Countess",
    "Capt",
    "Col",
    "Don",
    "Dr",
    "Major",
    "Rev",
    "Sir",
    "Jonkheer",
    "Dona"
]

full["Title"] = full["Title"].replace(
    rare_titles,
    "Rare"
)

full["Title"] = full["Title"].replace({
    "Mlle": "Miss",
    "Ms": "Miss",
    "Mme": "Mrs"
})

In [9]:
full["FamilySize"] = (
    full["SibSp"]
    + full["Parch"]
    + 1
)

In [10]:
full["IsAlone"] = (
    full["FamilySize"] == 1
).astype(int)

In [11]:
full["CabinKnown"] = (
    full["Cabin"]
    .notnull()
    .astype(int)
)

In [12]:
full.groupby("Title")["Age"].median()

Title
Master     4.0
Miss      22.0
Mr        29.0
Mrs       35.0
Rare      47.5
Name: Age, dtype: float64

In [13]:
full["Age"] = (
    full.groupby("Title")["Age"]
    .transform(
        lambda x: x.fillna(x.median())
    )
)

In [14]:
full["Fare"] = (
    full["Fare"]
    .fillna(
        full["Fare"].median()
    )
)

In [15]:
full["Embarked"] = (
    full["Embarked"]
    .fillna(
        full["Embarked"].mode()[0]
    )
)

In [16]:
full["AgeBand"] = pd.cut(
    full["Age"],
    bins=5,
    labels=False
)

In [17]:
full["FareBand"] = pd.qcut(
    full["Fare"],
    q=4,
    labels=False,
    duplicates="drop"
)

In [18]:
ticket_counts = (
    full["Ticket"]
    .value_counts()
)

In [19]:
full["TicketGroupSize"] = (
    full["Ticket"]
    .map(ticket_counts)
)

In [20]:
full.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title,FamilySize,IsAlone,CabinKnown,AgeBand,FareBand,TicketGroupSize
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr,2,0,0,1,0,1
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs,2,0,1,2,3,2
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss,1,1,0,1,1,1
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs,2,0,1,2,3,2
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr,1,1,0,2,1,1

In [21]:
full.to_csv(
    "engineered_features.csv",
    index=False
)

print("Saved successfully.")

Saved successfully.

In [22]:
print(full.shape)

(1309, 18)

In [23]:
print("New Features Created")

new_features = [
    "Title",
    "FamilySize",
    "IsAlone",
    "CabinKnown",
    "AgeBand",
    "FareBand",
    "TicketGroupSize"
]

for f in new_features:
    print(f)

New Features Created
Title
FamilySize
IsAlone
CabinKnown
AgeBand
FareBand
TicketGroupSize

In [24]:
from google.colab import files

files.download("engineered_features.csv")